################################################################################
# FEW-SHOT AUDIO EVAL CONFIGURATION FILE
################################################################################

#########################
# BASE SETTINGS
#########################
base:
  seed: 42
  num_workers: 0
  cuda: True

  path_to_configs: 'dataset_/configs_'
  results_path: #'RESULT FILES/resnet18_none_val_sample_stats.csv'


#########################
# MODEL/ENCODER
#########################
model:
  model_dir: #X:/Trained_model_storage/MT-SLVR Large Work/RN18 Main Models Extracted/none
  name: #resnet18 #resnet18/ast_tiny etc Prefix are added to the model depending on what adapter is selected
  dims: #2
  in_channels: #3
  input_tdim:  # Only needed for ast models # Now auto compute 
  encoder_fc_dim: #1000

adapters:
  #task_mode: None # series_adapters/parallel_adapters/bn/split for resnets
              # adaptformer_series/adaptformer_parallel/og_adapter for asts

  num_splits: #1 # Number of splits in the fc layer in backbone


#########################
# FEATURE EXTRACTION
#########################
extraction:
  batch_size: 1 # Has to stay at 1 (allows for variable sets to be processed correctly)
  num_workers: 0

#########################
# FEW-SHOT TASKS
#########################
task:
  n_way: #5
  k_shot: #1
  q_queries: #1
  num_tasks: #10000
  batch_size: 1
  split: #val # test/val
  hardness: [avg]

#########################
# CLASSIFIER
#########################
classifier:
  type: #sklin #linear/NCC/sklin
  adapt_steps: 20
  lr: 0.01


#########################
# DATA
#########################
data:
  source_dataset: FSD50K
  norm: sample #sample/global/None/l2 # We use per-sample wise stats by default
  stats_file: dataset_/stats_/FSD50k_train_stats.npy
  ext: '.npy'

  in_dims: 2
  in_channels: 3

data_paths:
  ESC: 'X:/Datasets/ESC-50-master/Sorted_npy'
  Kaggle18_5s: X:/Datasets/Kaggle AudioSet/Raw_5_second_npy
  NSYNTH: 'X:/Datasets/NSynth/nsynth_npy_no_norm'
  VoxCeleb_5s: 'X:/Datasets/VoxCeleb1/voxceleb_5s_raw'
  BirdClef_5s: 'X:/Datasets/Rw Datasets/BirdClef_npy_pruned_5s_raw'

  Watkins_5s: 'X:/Datasets/Wakins/watkins_5s_raw_npy'
  SCV2_1s: 'X:/Datasets/Speech Commands/V2/SCV2_1s_raw_npy'

  SAA_5s: X:/Datasets/Speech Accent Archive/sorted_recordings_5s_raw
  CommonVoice_5s: X:/Datasets/Common_Voice/reduced_raw_5s
  CremaD_5s: X:/Datasets/CremaD/sorted_5s_raw

# Whether to precompute feats or not
use_feats:
  ESC: True
  Kaggle18_5s: True
  NSYNTH: False
  VoxCeleb_5s: False
  BirdClef_5s: True

  Watkins_5s: True
  SCV2_1s: False

  SAA_5s: True
  CommonVoice_5s: False
  CremaD_5s: True


# Fourier transform params
ft_params:
  sample_rate: 16000
  n_mels: 128
  n_fft: 1024
  hop_length: 512
  power: 2
