
target_data:
  # We want to use the stats from training
  variable: True
  name: 'ESC'
  norm: 'global'
  type: 'variable_raw' # variable_spec/spec/raw
  
  all_test: False

  fixed_path: 'dataset_/splits_/ESC_split.npy'
