
target_data:
  # We want to use the stats from training
  variable: False
  name: 'ESC'
  norm: 'global'
  type: 'raw' # variable_spec/spec/raw
  fixed: True
  
  all_test: False

  fixed_path: 'dataset_/splits_/ESC_split.npy'
