
target_data:
  variable: True
  name: 'Kaggle18_5s' #Kaggle_18
  norm: 'global'
  type: 'variable_raw' # variable_spec/spec/raw
  fixed: True
  
  all_test: False

  fixed_path: 'dataset_/splits_/kaggle_split.npy'
