target_data:
  # We want to use the stats from training
  variable: False
  name: 'NSYNTH' #Kaggle_18
  norm: 'global'
  type: 'raw' # variable_spec/spec/raw
  
  all_test: False
  
  fixed_path: 'dataset_/splits_/nsynth_split.npy'
