target_data:
  # We want to use the stats from training
  variable: True
  name: 'NSYNTH' 
  norm: 'global'
  type: 'variable_raw' # variable_spec/spec/raw
  
  all_test: False
  
  fixed_path: 'dataset_/splits_/nsynth_split.npy'
