
target_data:
  # We want to use the stats from training
  variable: True
  name: 'SAA_5s' #Kaggle_18/BirdClef_pruned_5s
  norm: 'global'
  type: 'variable_raw' # variable_spec/spec
  fixed_path: 'dataset_/splits_/saa_split.npy'

  all_test: True



