
target_data:
  # We want to use the stats from training
  variable: True
  name: 'SCV2_1s' #Kaggle_18/BirdClef_pruned_5s
  norm: 'global'
  type: 'variable_raw' # variable_spec/spec
  fixed: 'dataset_/splits_/sc_split.npy'

  all_test: True



